version: 0.2

phases:
  install:
    commands:
      - sudo apt-get update
      - sudo apt-get install maven -y
      - mvn --version

  build:
    commands:
      - mvn clean install -DskipTests

  post_build:
    commands:
      - echo "Transfer the artifact"
      - aws s3 cp target/*.jar s3://aws-s3-bucket-demo-nal/app.jar

artifacts:
  files:
    - target/*.jar
